name: Create Tag on Push

on:
  push:
    tags:
      - '*android'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: cimg/node:22.0.0-browsers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.3'
          cache: 'npm'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromedriver
          google-chrome --version
          chromedriver --version

      - name: Check Node.js version
        run: node -v

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          if [ ! -d "node_modules" ]; then
            npm ci
          fi

      - name: Build and Pack (PR)
        run: |
          npm run build:prod
          npm pack ./dist
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}